# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      containers:
        - name: my-ubuntu
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 81
